version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - $HOME/.poetry/bin/poetry config virtualenvs.create false
      - $HOME/.poetry/bin/poetry install
